django-basics/mm_blog/blog_post_app/urls.py
from django.urls import path
from . import views

app_name = "blog_post_app"

urlpatterns = [
    path("", views.login_view, name="login"),
    path("register/", views.registration_view, name="register"),
    path("home_page/", views.get_home_view, name="get-home"),
    path("home_page/add", views.post_home_view, name="post-home"),
    path("home_page/comment/add/<int:post_pk>/", views.post_comment_view, name="add-comment"),
    path("home_page/positive_rating/<int:post_pk>/<str:is_positive>", views.blog_post_voting_view,
         name="add-rating"),
]

django-basics/mm_blog/blog_post_app/models.py
import django
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True, blank=False)
    password = models.CharField(max_length=100)
    registration_date = models.DateTimeField("the date user is registered", default=django.utils.timezone.now)

    def __str__(self):
        return f"id: {self.pk}, username: {self.username}, email: {self.email}, password: {self.password}, registration_date: {self.registration_date}"


class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(max_length=240, default=None)
    text = models.TextField(max_length=1024)

    def __str__(self):
        return f"id: {self.pk}, title: {self.title}, text: {self.text}"


class Comment(models.Model):
    text = models.TextField(max_length=1024)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Hashtag(models.Model):
    value = models.CharField(max_length=45)
    blog_posts = models.ManyToManyField(BlogPost)

    def __str__(self):
        return f"id: {self.pk}, value: {self.value}"


class BlogPostVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post_voting_user')
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='blog_post_voting')
    status = models.BooleanField()

    def __str__(self):
        return f"vote_status: {self.status},  user: {self.user}, blog post: {self.blog_post}"

django-basics/mm_blog/blog_post_app/forms.py
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User

django-basics/mm_blog/blog_post_app/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .utils import Utils
from .models import *
from .forms import *


def login_view(request):
    form = UserLoginForm(request, data=request.POST)
    if form.is_valid() and form.user_cache is not None:
        user = form.user_cache
        if user.is_active:
            login(request, user)

            return HttpResponseRedirect(reverse("blog_post_app:get-home"))
    else:
        context = {'form': form }
        return render(request, "blog_post_app/login.html", context)


def registration_view(request):
    form = UserRegisterForm(request.POST)
    if form.is_valid():
        form.save()

    context = {'form': form}

    return render(request,  "blog_post_app/register.html", context)


@login_required
def get_home_view(request):
    blog_posts = BlogPost.objects.all()
    negative_count = BlogPost.objects.filter(blog_post_voting__status=False).count()
    positive_count = BlogPost.objects.filter(blog_post_voting__status=True).count()

    context = {
        "blog_post": BlogPost(),
        "blog_posts": blog_posts,
        "comment_text": str(),
        "hashtag_string": str(),
        "negative_count": negative_count,
        "positive_count": positive_count
    }

    return render(request, "blog_post_app/home.html", context)


def post_home_view(request):
    title = request.POST.get('blog_post.title')
    text = request.POST.get('blog_post.text')
    hashtag_string = request.POST.get("hashtag_string")

    hashtags = Utils.modify_hashtag_raw_string(hashtag_string)
    print(hashtags)
    blog_post = BlogPost.objects.create(title=title, text=text, user=request.user)

    for hashtag in hashtags:
        saved_hashtag = Hashtag.objects.create(value=hashtag)
        blog_post.hashtag_set.add(saved_hashtag)

    blog_post.save()

    return HttpResponseRedirect(reverse("blog_post_app:get-home"))


def post_comment_view(request, post_pk):
    comment_text = request.POST.get('comment_text')
    found_blog_post = get_object_or_404(BlogPost, pk=post_pk)
    new_comment = Comment(text=comment_text, post=found_blog_post, user=request.user)
    new_comment.save()

    return HttpResponseRedirect(reverse("blog_post_app:get-home"))


def blog_post_voting_view(request, post_pk: int, is_positive: str):
    votes = BlogPostVote.objects.filter(blog_post__pk=post_pk, user=request.user)
    is_positive = is_positive.lower() == 'true'

    if not votes.exists():
        BlogPostVote.objects.create(user=request.user, blog_post_id=post_pk, status=is_positive)
    else:
        vote = votes.first()
        if vote.status != is_positive:
            vote.delete()
            BlogPostVote.objects.create(user=request.user, blog_post_id=post_pk, status=is_positive)

    return HttpResponseRedirect(reverse("blog_post_app:get-home"))

django-basics/mm_blog/blog_post_app/templates/blog_post_app/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Blog Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog_post_app/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Create a New Blog Post</h1>
        <form action="{% url 'blog_post_app:post-home' %}" method="post">
        {% csrf_token %}
            <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control" name="blog_post.title" id="title">
            </div>
            <div class="form-group">
                <label>Content</label>
                <textarea class="form-control" rows="6" id="content" name="blog_post.text"></textarea>
            </div>
            <div class="form-group">
                <label>Hashtags</label>
                <input type="text" class="form-control" name="hashtag_string" id="hashtag">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <hr>
        <div class="post-section">
            <h2 style="text-align: center;">Available Posts</h2>
            <hr>
            {% for blog_post in blog_posts %}
            <div class="post">
                <div class="actions">
                    <h4>{{ blog_post.title }}</h4>
                </div>
                <hr>
                <p>{{ blog_post.text|urlize }}</p>
                <hr>
                <p> Hashtags:
                    {% for hashtag in blog_post.hashtag_set.all %}
                    <a href="#">{% if hashtag.value|slice:":1" != "#" %}#{% endif %}{{ hashtag.value }}</a>
                    {% endfor %}
                </p>
                <hr>
                <div class="d-flex align-items-center">
                    <p class="mr-3">{{ positive_count }} Likes</p>
                    <a type="button" href="{% url 'blog_post_app:add-rating' blog_post.pk True %}" class="btn btn-success mr-3">👍</a>
                    <p class="ml-3">{{ negative_count }} Dislike</p>
                    <a type="button" href="{% url 'blog_post_app:add-rating' blog_post.pk False %}" class="btn btn-danger ml-3">👎</a>
                </div>
                <hr>
                <div class="comments">
                    <h5>Comments:</h5>
                    <hr>
                    {% for comment in blog_post.comment_set.all %}
                    <div class="">{{ comment.user.username }}</div>
                    <div class="comment">{{ comment.text }}</div>
                    <hr>
                    {% endfor %}
                    <form action="{% url 'blog_post_app:add-comment' blog_post.pk %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea class="form-control mt-3" name="comment_text" rows="3" placeholder="Add a comment"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Post Comment</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script>
    // Logic for thumb-up and thumb-down actions
    $('.thumb-up').click(function() {
        // Add your logic here for thumb-up action
        console.log('Thumb up clicked');
    });

    $('.thumb-down').click(function() {
        // Add your logic here for thumb-down action
        console.log('Thumb down clicked');
    });
</script>
</body>
</html>

django-basics/mm_blog/blog_post_app/templates/blog_post_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog_post_app/style.css' %}">
</head>
<body>
<div class="container">
<h1> Login into your account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form }}
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
</body>
</html>

django-basics/mm_blog/blog_post_app/templates/blog_post_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog_post_app/style.css' %}">
</head>
<body>
<div class="container">
<h1> Register your account</h1>
    {% if has_user_exists == True %}
    <p class="text-danger">User with that username already exits</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='Register'/>
    </form>
</div>
</body>
</html>